travis-build: allow suppressing of formatter errors on selected distros
Some distributions, notably Ubuntu 16.04 and OpenSUSE Tumbleweed (as of
22.10.17) ship an older version of uncrustify. This version may report
formatting errors.

diff --git a/extra/travis-build b/extra/travis-build
--- a/extra/travis-build
+++ b/extra/travis-build
@@ -121,8 +121,12 @@ install_deps() {
 
 build() {
     set -ex
-    ./extra/fmt check && \
-        mkdir -p build && \
+    ./extra/fmt check || {
+        echo "WARNING: code formatting check failed"
+        [ -z "${SUPPRESS_FMT}" ] && false
+    }
+
+    mkdir -p build && \
         cd build && \
         meson .. && \
         ninja && \
@@ -136,6 +140,14 @@ build() {
 
 build_in_container() {
     install_deps $1
+
+    # distro specific quirks
+    case "$1" in
+        ubuntu-xenial|opensuse)
+            echo "$1 is using an outdated version of uncrustify, suppress formatting errors"
+            export SUPPRESS_FMT=1
+            ;;
+    esac
 
     build
 }
